### ISSUE TITLE
Support toolchain toml

### ISSUE THREAD

**Issue by fzzr-** [pontem-network/pontem#180]
Currently we're using [fork by @zephraph][] with patch for the subject, since #176.

We have to switch back to using original [actions-rs/toolchain][] when that [PR][] and [issue][] closed.
Just replace `zephraph/toolchain@support-toolchain-toml` to `actions-rs/toolchain@v1` anywhere.

Checklist:
- [ ] tests
- [ ] release
- [ ] coverage

[actions-rs/toolchain]: https://github.com/actions-rs/toolchain/
[fork by @zephraph]: https://github.com/zephraph/toolchain/tree/support-toolchain-toml
[issue]: https://github.com/actions-rs/toolchain/issues/126
[PR]: https://github.com/actions-rs/toolchain/pull/209

**Comment by zephraph** [comment]
Instead of using my fork I'd recommend using https://github.com/oxidecomputer/actions-rs_toolchain. I migrated it to @oxidecomputer's org because we have a vested interest in Rust and its infrastructure and there's more eyes there beyond just my own. If other changes come up that need to be added, that's where it'll happen. I will, of course, continue to work to try to get these updates merged upstream.

**Comment by fzzr-** [comment]
@zephraph thanks! [Done](https://github.com/pontem-network/pontem/pull/186).
